const x = 7;

try {
  x = 2;
} catch (err) {
  console.log(`Erro: ${err}`);
}
